In [3]:
import pandas as pd

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/atlantico-academy/datasets/main/mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [9]:
df.to_csv("../data/raw/data.csv", index=False)

In [10]:
import pandas as pd

dicionario = pd.DataFrame([
    { 
        "variavel": "mpg",
        "descricao": "representa uma medida de eficiencia de combustivel",
        "tipo": "Numerico",
        "subtipo": "Continuo"
    },
    { 
        "variavel": "cylinders",
        "descricao": "representa uma contagem de cilindros, um valor inteiro",
        "tipo": "Numerico",
        "subtipo": "Discreto"
    },
    { 
        "variavel": "displacement",
        "descricao": "representa o volume do motor, uma medida contínua",
        "tipo": "Numerico",
        "subtipo": "Continuo"
    },
    { 
        "variavel": "horsepower",
        "descricao": "representa a potência do motor, uma medida contínua",
        "tipo": "Numerico",
        "subtipo": "Continuo"
    },
    { 
        "variavel": "weight",
        "descricao": "representa o peso do carro, uma medida contínua",
        "tipo": "Numerico",
        "subtipo": "Continuo"
    },
    { 
        "variavel": "acceleration",
        "descricao": "representa o tempo de aceleração do carro, uma medida contínua",
        "tipo": "Numerico",
        "subtipo": "Continuo"
    },
    { 
        "variavel": "model_year",
        "descricao": "Representa o ano do modelo do carro, um valor inteiro",
        "tipo": "Numerico",
        "subtipo": "Discreto"
    },
    { 
        "variavel": "origin",
        "descricao": "representa a origem do carro, uma categoria sem ordem intrínseca: 'usa', 'japan', 'europe'",
        "tipo": "Categorico",
        "subtipo": "Nominal"
    },
    { 
        "variavel": "name",
        "descricao": "representa o nome completo do carro, uma categoria sem ordem intrínseca",
        "tipo": "Categorico",
        "subtipo": "Nominal"
    }
])


dicionario.to_csv("../data/external/dictionary.csv", index=False)

dicionario

,variavel,descricao,tipo,subtipo
0,mpg,representa uma medida de eficiencia de combust...,Numerico,Continuo
1,cylinders,"representa uma contagem de cilindros, um valor...",Numerico,Discreto
2,displacement,"representa o volume do motor, uma medida contínua",Numerico,Continuo
3,horsepower,"representa a potência do motor, uma medida con...",Numerico,Continuo
4,weight,"representa o peso do carro, uma medida contínua",Numerico,Continuo
5,acceleration,"representa o tempo de aceleração do carro, uma...",Numerico,Continuo
6,model_year,"Representa o ano do modelo do carro, um valor ...",Numerico,Discreto
7,origin,"representa a origem do carro, uma categoria se...",Categorico,Nominal
8,name,"representa o nome completo do carro, uma categ...",Categorico,Nominal